internal/executor/executor.go, webui/js/ActionButton.js
Was experimenting with executing commands without using a shell (`sh -c`), but found that we didn't need to drop the shell support to get stderr working properly. Had been assigning stderr completely wrong until now!
=> bugfix: Working stderr!

openrc-OliveTin
This service file should really just be called "OliveTin" when installing, but I've named it `openrc-OliveTin` for convenience at the moment. Basically, if you follow the usual manual installation guide, substituting this file for `OliveTin.service` and putting it in `/etc/init.d/` will work just fine.
(Though it has to be made executable, it isn't at present)
The service can be enabled on boot with `rc-update add OliveTin`, and started/stopped with `service OliveTin start/stop`. I have tested this on Alpine Linux, but it *should* also work on Gentoo and any other openRC-based system.
=> Created a service file for OpenRC (Alpine Linux/Gentoo)

OliveTin.proto, cmd/OliveTin/main.go, internal/grpcapi/grpcApi.go, internal/installationinfo/buildinfo.go, internal/installationinfo/runtimeinfo.go, internal/installationinfo/sosreport.go, internal/updatecheck/updateCheck.go
This PR creates a sosreport (https://github.com/sosreport/sos) style debug output in the logs that is extremely helpful for helping out people with support issues. A sosreport can be generated by going to `/api/sosreport`, and the content is logged by OliveTin's standard output.
Here is an example; 
```
commit: nocommit
version: dev
date: nodate
os: linux
osreleaseprettyname: PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
arch: amd64
incontainer: false
lastbrowseruseragent: ""
countofactions: 7
loglevel: INFO
```
=> feature: sosreport

.github/workflows/build-snapshot.yml
The integration-tests GitHub artifact was uploading 6000+ node_modules files, which takes 15+ minutes. Anyone wanting to use these integration-tests in this way can `npm install` them much faster, without any risk.
=> cicd: Remote node_modules from integration tests upload

internal/acl/acl.go, internal/grpcapi/grpcApi.go
This reduces log spam seen when setting logLevel: DEBUG, by changing several log messages to TRACE instead.
When debugging another issue with logLevel set to DEBUG, on each http request OliveTin was generating something like 30 lines of output - which is ridiculous. 
For debugging deep ACL issues, TRACE is more appropriate anyway.
=> feature: Reduce debug log spam in ACL/getDashboardComponents

internal/httpservers/singleFrontend.go, internal/websocket/websocket.go
1) The single HTTP frontend was "listening" on /, not /websocket - it was still working because requests to / were checking for the Upgrade header, but this makes reverse proxy configuration more difficult than it needs to be. 
2) The upgrader was refusing reverse proxies because of the CheckOrigin function - so make this permissive, with a note in the code as to why - see the code comment.
=> bugfix: #173 Websocket fixes 

internal/executor/executor.go
This is a minor PR that adjusts a log message, for example; 
```
INFO Action requested                              actionTitle="Run backup script"
WARN Blocked from executing. This would mean this action is running 2 times concurrently, but this action has maxExecutions set to 1.  actionTitle="Run backup script"
```
=> feature: Add actionTitle to blocked log messages

webui/index.html, webui/js/ExecutionButton.js, webui/js/ExecutionDialog.js, webui/style.css
The Execution dialog would only show the first result because it wasn't being properly reset each time it was invoked.
=> bugfix: Execution dialog would only show first result

config.yaml, internal/config/config.go, internal/oncron/cron.go
This adds seconds support as optional to cron (disabled by default). https://docs.olivetin.app/exec-cron.html
=> feature: #202 Cron seconds support optional. Example in default config.

Makefile
The last release introduced parcel to bundle assets, which uses absolute URIs by default. This PR changes the "public-url" to ".", making the asset URIs for Javascript, Stylesheets, etc relative to the document.
This is necessary for people who proxy OliveTin with a different document path (#192).
=> bugfix: #230 Set public-url in parcel to .

webui.dev/style.css
Use dvh (introduced in all browsers in 2022), as vh is fixed now-a-days.
=> bugfix: #233 switch sidebar to 100dvh

internal/entityfiles/entityfiles.go
This is simply something useful for development purposes - it searches {configdir}/var/entities when entities use a relative path.
=> cicd: Try {configdir}/var/entities/ when looking for entity files as well

internal/executor/executor.go
This is necessary because signals were ignored.
=> Bug ignored signals

OliveTin.proto, cmd/OliveTin/main.go, internal/config/config_reloader.go, internal/websocket/websocket.go, webui.dev/js/websocket.js, webui.dev/main.js
OliveTin stopped "refreshing" the web UI when it moved to web sockets. This change re-introduces a "config changed event", forcing the UI to refresh.
=> bugfix: The web interface now refreshes when the config file is changed!

internal/config/config.go, internal/executor/arguments.go, internal/executor/arguments_test.go
Addresses a very old feature request - #36
=> Nullable args

internal/onfileindir/fileindir.go
=> fmt: onfileindir

integration-tests/package.json, webui.dev/package.json
OliveTin has always been AGPL V3 only. This os declared by the top level LICENSE file. 
Npm just defaults to ISC.
=> doc: fix default licenses in package.json

webui.dev/js/marshaller.js, webui.dev/js/websocket.js, webui.dev/main.js
=> feature: OliveTin now relies on websocket, and will show a big error if it isn't available

OliveTin.proto, cmd/OliveTin/main.go, internal/executor/executor.go, internal/executor/executor_actions.go, internal/executor/executor_test.go, internal/grpcapi/grpcApi.go, internal/grpcapi/grpcApiActions.go, internal/grpcapi/grpcApi_test.go, internal/websocket/websocket.go
This is a pretty major OliveTin change. 
OliveTin actions in the configuration file do not necessarily map 1:1 to actions that can be started. The most notable example of this is entities, which "generate" buttons on the web UI from a single config entry. This means that OliveTin has to generate an ID for each individual button that can be started (as going by action titles with variables in them won't work). OliveTin has previously maintained this map in the grpc API, eg: 
- "1234" -> Start {{ container.Name }} | Plex
- "4567" -> Start {{ container.Name }} | Minecraft
- "8910" -> Start {{ container.Name }} | Haproxy
The problem is that this map is only updated / generated on requests to the API, specifically `GetDashboardComponents`. This created the following subtle problems;
- The …
=> feature: The executor now controls the public action map - meaning actions work without the API, and pages load faster (and much more!)

OliveTin.proto, internal/config/config.go, internal/config/emoji.go, internal/config/emoji_test.go, internal/config/sanitize.go, internal/grpcapi/grpcApi.go, internal/grpcapi/grpcApiDashboard.go, internal/httpservers/webuiServer.go, webui.dev/js/marshaller.js, webui.dev/main.js
Feature requested on discord. Will document soon. 
3 new config options;
`DefaultIconForDirectories`, `DefaultIconForActions`, `DefaultActionForBack`
Dashboard components now have a `icon` property, which is used for folders;
```
dashboards:
- title: My dashboard
contents:
- title: My Folder
icon: &#1F600
contents:
...
```
=> feature: Customizable default directory, back and action icons

integration-tests/Makefile, integration-tests/configs/sleep/config.yaml, integration-tests/lib/elements.js, integration-tests/runner.mjs, integration-tests/test/sleep.js, internal/grpcapi/grpcApi.go, webui.dev/js/ExecutionDialog.js
=> feature: Vastly improved logs and tests for killing actions

cmd/OliveTin/main.go, internal/httpservers/webuiServer.go, internal/installationinfo/runtimeinfo.go, internal/updatecheck/updateCheck.go
This change stops OliveTin from generating installation IDs, and sending them with CurrentVersion to the server. See #93 for some of the discussion and the justification for this change. 
The "update service" now just hosts a simple .json file, see the related change here; https://github.com/OliveTin/update-check.olivetin.app/commit/dcd5cc49abca0b62d3bd7017533387d8fb80a79a
=> feature: No more tracking in update checking! :-) (#93)

.github/workflows/build-snapshot.yml, .github/workflows/build-tag.yml, .github/workflows/codestyle.yml
Previous builds were set to use the version statically, 1.18. Updating the actions to use go.mod (1.21). 
This might also help with some weird windows issues seen recently.
=> depbump: Upgrade Go to 1.21

internal/executor/executor.go
Just after OliveTin 2024.04.261, I added support for all arguments to be exposed as environment variables to running actions, with this code; 
```go
+       for k, v := range req.Arguments {
+               ret = append(ret, fmt.Sprintf("%v=%v", strings.ToUpper(k), v))
+       }
```
This is fine, but sometimes arguments don't contain a name (this isn't necessarily required, for example with `type: confirm`);
```yaml
actions:
- title: foo
shell: echo "foo"
arguments:
- type: confirm
```
So OliveTin was trying to set an environment variable called "" - the name of the "confirm" type argument. Linux silently ignored this, but Windows exits with this weird error message - "exec/fork" ... "The parameter is incorrect"
The solution, therefore, is to not try and set environment variables with the …
=> bugfix: Empty environment variable names causing exec failures on Windows, thanks @sirjmann92 !

cmd/OliveTin/main.go, internal/config/config.go, internal/grpcapi/grpcApi.go, internal/httpservers/restapi.go
=> feature: #350 Environment variable PORT can be used to override the default 1337, and internal services will calculate their port based on that

integration-tests/lib/elements.js, webui.dev/index.html, webui.dev/js/ActionStatusDisplay.js, webui.dev/js/ExecutionDialog.js, webui.dev/js/marshaller.js, webui.dev/style.css
* Combines "Start Time" and "Finish Time" into "Duration"
* Combines "Exit Code" and "Status" into status
* Uses the same code to display status in the execution dialog, and log table. 
* Removes the hide/show output toggle, as it was causing weird scrolling issues when fullscreen.
* Stretches the execution dialog to the full height of the browser window when "expanded".
* Stretches the xterm output to use as much space as possible in the execution dialog.
* Rezies the xterm output when the execution dialog size is toggeled.
=> feature: Cleanup execution dialog, and log display status.

internal/executor/arguments.go, internal/executor/executor.go, webui.dev/js/marshaller.js, webui.dev/style.css
#419 #420
So, I can only assume my brain was turned off when I was patching shellAfterCompleted recently.
- The executor `stepExecAfter` call to `parseActionArguments` was silently failing, with an error message of arguments like `output` not being found, and it was returning a empty command to execute (literally ""), which executed "sucessfully". This led to REALLY confusing output.
- I fixed the printing of the error message, and if an error is returned, nothing will be executed for shellAfterCompelted.
- I broke out the parseActionArguments call into a simpler function that skips the type check, which `shellAfterCompleted` can then use. 
- The log messages kept on appending stdout, meaning that once this was fixed, the logs were getting spammed like crazy. It looked really weird. …
=> bugfix: Fixed unusual issues that slipped through with shellAfterCompleted 

internal/executor/executor.go
rationale: As a user I want to be able to create an apprise message containing a link to the log. In order to do that I need `ot_executionTrackingId`
Tested with an action having 
```yaml
- title: "Test Notification"
icon: <iconify-icon icon="fluent:folder-list-16-filled"></iconify-icon>
popupOnStart: execution-dialog-stdout-only
shell: "date"
shellAfterCompleted: 'apprise -vvv -c /config/apprise.yaml -t "Notification: testing" -b "Check the logs at http://localhost:1337/logs/${OT_EXECUTIONTRACKINGID}"'
maxConcurrent: 1
```
The fakeRequest bits feels hacky, but it seems to work at least
Done partly due to #419 
```
make daemon-compile
go env -w GOARCH=arm GOARM=6
go: unsupported GOOS/GOARCH pair darwin/arm
make: *** …
```
=> feature: pass ot_ args to shellAfterCompleted

internal/config/config.go, internal/grpcapi/grpcApi.go, internal/httpservers/restapi.go, internal/httpservers/webuiServer.go, webui.dev/main.js
This is an initial attempt of adding a feature to navigate to a configured url if configured and user is not authenticated.
basically
As a end user I want to end up on a login page if I am not authenticated
so that it is clear that I am not authenticated and can easily log in again.
I do not know the codebase well yet, so it is quite possible that I have done something stupid and/or missed something obvious.
Opening PR early for feedback.
Known issues: 
- `make daemon-unittests` panic for some reason
- `make daemon-compile`: go: unsupported GOOS/GOARCH pair darwin/arm
- docs
=> Make it possible to redirect to a login url unless authenticated

webui.dev/main.js
This is a followup to #347 
Turns out that the backend is now returning 403 and not 401. (I am certain that I saw 401 before, but unclear if I messed up my testing somehow or if possibly #430 changed the error code, anyhow, 403 seems to be correct now anyway)
=> bugfix: Turns out this should now be 403 instead
