internal/config/config.go, internal/httpservers/webuiServer.go, webui/main.js
=> feature: Show/Hide footer

integration-tests/configs/config.hiddenNav.yaml, internal/config/config.go, internal/httpservers/webuiServer.go, webui/main.js
=> bugfix: Rename "HideNavigation" to "ShowNavigation"

cmd/OliveTin/main.go
=> feature: issue #38 - Config Directories

OliveTin.proto, config.yaml, internal/config/config.go, internal/grpcapi/grpcApiActions.go, webui/js/ArgumentForm.js, webui/style.css
Add simple text descriptions to action arguments.
=> feature: #61 - Descriptions in arguments

internal/config/config.go, internal/httpservers/restapi.go
=> extract hardcoded jwt claim names into config

cmd/OliveTin/main.go, internal/config/config.go, internal/oncron/cron.go
This PR introduces basic CRON support.
=> feature: Cron support

.goreleaser.yml
Recommended by bestpractices.dev
=> Add upgrade warnings + breaking changes

.gitignore, OliveTin.proto, config.yaml, internal/config/config.go, internal/config/sanitize.go, internal/executor/executor.go, internal/grpcapi/grpcApi.go, internal/websocket/websocket.go, webui/index.html, webui/js/ExecutionButton.js, webui/js/ExecutionDialog.js, webui/style.css
This PR add support for maxConcurrent on accounts, blocking execution beyond that number.
=> feature: #146 Support for maxConcurrent

webui/js/ActionButton.js
=> fmt: ActionButton.js

cmd/OliveTin/main.go, internal/config/config.go, internal/onfileindir/fileindir.go, webui/js/ActionButton.js
=> feature: onfileindir

webui/index.html, webui/js/marshaller.js, webui/main.js, webui/style.css
This allows users to search logs, by providing a little search input box above the table.
=> Feature search logs

config.yaml, internal/config/config.go, internal/config/config_helpers.go, internal/executor/executor.go
This PR adds notification support essentially, by adding "shellAfterComplete".
=> Notification support

webui/index.html, webui/js/ActionButton.js, webui/js/ExecutionButton.js, webui/style.css
This gets rid of the rather awful "Not executed yet", and "dropdown" status for execution buttons, and instead shows a button kind of "history" that scrolls.
=> feature: Better UI for execution buttons

webui/style.css
=> #197 Dialog has min-width, but should be max-width

internal/acl/acl.go
=> ACL check was broken, addToEveryAction should come first

OliveTin.proto
Changed protobuf from POST to GET
=> #201 - startActionByAlias should be HTTP GET

integration-tests/.mocharc.yml, integration-tests/Makefile, integration-tests/README.md, integration-tests/Vagrantfile, integration-tests/envVagrant.sh, integration-tests/mochaSetup.mjs, integration-tests/runner.mjs, integration-tests/test/general.mjs, integration-tests/test/hiddenFooter.mjs, integration-tests/test/hiddenNav.mjs, integration-tests/test/multipleDropdowns.js
Adds better support for running tests im VMs
=> cicd: Improve tests

webui/js/ArgumentForm.js, webui/style.css
=> bugfix: Argument form on smaller screens

config.yaml, internal/config/emoji.go
=> feature: clock and ashtonished emoji

config.yaml, webui/js/ArgumentForm.js
=> feature: #69 - Add action confirmation

webui/style.css
=> bugfix: #216 - fix scroll in chrome

webui/index.html, webui/style.css
=> Markup improvements

OliveTin.proto, integration-tests/test/multipleDropdowns.js, internal/config/config.go, internal/grpcapi/grpcApi.go, internal/grpcapi/grpcApiDashboard.go, internal/httpservers/webuiServer.go, webui/index.html, webui/js/ActionButton.js, webui/js/marshaller.js, webui/main.js, webui/style.css
This PR introduces dashboards, which addresses #151 , #64 , #16 and #15 .
=> feature: Dashboards, at long last

config.yaml, internal/config/config.go, var/entities/containers.yaml
This is the beginning of entity support - vars from files
=> Beginning of entity support: Vars from files

config.yaml, internal/config/config.go, internal/config/emoji.go, internal/config/sanitize.go, webui/index.html, webui/js/ActionButton.js, webui/js/ExecutionButton.js, webui/js/ExecutionDialog.js, webui/js/ExecutionFeedbackButton.js, webui/js/marshaller.js, webui/js/websocket.js, webui/main.js, webui/style.css
=> feature: popupOnStart allows for many feedback options when actions are started

config.yaml
=> feature: Nicer container dashboard example in the default config

webui.dev/js/marshaller.js, webui.dev/main.js
This wasn't working previously
=> bugfix: PageTitle works again

OliveTin.proto, internal/grpcapi/grpcApi.go, internal/grpcapi/grpcApiDashboard.go, webui.dev/js/marshaller.js, webui.dev/style.css
=> Msot recent execution output on the dashboard.

README.md, webui.dev/index.html, webui.dev/js/ActionButton.js, webui.dev/style.css
=> feature: Rounded buttons... because apparently they look modern?!

integration-tests/test/multipleDropdowns.js
=> cicd: Flakey test on dropdowns

cmd/OliveTin/main.go, internal/config/config.go, internal/executor/arguments.go, internal/filehelper/file_change_notify.go, internal/filehelper/file_touch.go, internal/oncalendarfile/calendar.go, webui.dev/js/ArgumentForm.js
=> feature: Exec on Calendar file support

internal/executor/arguments.go, webui.dev/js/ArgumentForm.js
=> feature: #56 custom tegex for arguments

Dockerfile, Dockerfile.arm64
Apprise is exceptionally useful for OliveTin, to male ot easy to send notifications
=> feature: add apprise

internal/config/config.go, internal/executor/arguments.go, internal/grpcapi/grpcApiActions.go, internal/grpcapi/grpcApiDashboardEntities.go, internal/stringvariables/entities.go
=> feature: Entitiys in dropdowns #247

OliveTin.proto, internal/config/config.go, internal/grpcapi/grpcApiActions.go, webui.dev/js/ArgumentForm.js
=> Argument suggestions

webui.dev/js/marshaller.js
Set sidebar visibility to hidden after the animation goes off sreen
=> bugfix: sidebar nav wont tab when hidden

webui.dev/style.css
Folder buttons were not rounded
=> bugfix: rounded buttons for folders

webui.dev/style.css
=> bugfix: dark mode headr

cmd/OliveTin/main.go, internal/config/config.go, internal/config/config_helpers.go, internal/httpservers/webuiServer.go, webui.dev/.parcelrc, webui.dev/index.html, webui.dev/main.js, webui.dev/package-lock.json, webui.dev/package.json
This introduces a custom-webui directory that is created in the same directory as where the config.yaml is found. It will try to create a "themes" folder in this custom-webui directory as well.
It is hoped that this makes it much easier to install themes and custom webui content by keeping everything in one place.
=> custom-webui and faster theme loading

.github/workflows/build-snapshot.yml
=> cicd: Dont build snapshot on tag

go.mod, go.sum, internal/config/config.go, internal/httpservers/restapi.go, internal/httpservers/restapi_auth_jwt.go, internal/httpservers/singleFrontend.go
=> feature: JWT Validation wip for Cloudflare

README.md
=> doc: typo #266

internal/acl/acl.go, internal/config/config.go, internal/grpcapi/grpcApi.go
=> feature: #135 Permissions for logs

Dockerfile, Dockerfile.arm64
=> feature: #276 add jq to containers

internal/entityfiles/entityfiles.go, internal/executor/executor.go, internal/filehelper/file_change_notify.go, internal/oncalendarfile/calendar.go, internal/onfileindir/fileindir.go
Much of the inotify code was duplicated and messy,  this moves it all in to one package.
=> bugfix: Move all inotify to filehelper

internal/entityfiles/entityfiles.go, internal/stringvariables/entities.go, internal/stringvariables/entities_test.go, internal/stringvariables/map_test.go
=> cicd: Increase coverage

Makefile, webui.dev/package-lock.json, webui.dev/package.json
=> bugfix: Dont rename logo filenames

OliveTin.proto, internal/websocket/websocket.go, webui.dev/js/marshaller.js, webui.dev/js/websocket.js
=> bugfix: Unexpected message #283

internal/entityfiles/entityfiles.go, internal/onfileindir/fileindir.go
=> bugfix: Start filewatcher on different goroutines

webui.dev/js/ActionButton.js
=> bugfix: Update icon on buttons

integration-tests/Makefile, integration-tests/configs/entities/config.yaml, integration-tests/configs/entities/entities/servers.yaml, integration-tests/configs/general/config.yaml, integration-tests/configs/pageTitle/config.yaml, integration-tests/lib/elements.js, integration-tests/package-lock.json, integration-tests/package.json, integration-tests/test/entities.js, integration-tests/test/general.mjs, integration-tests/test/multipleDropdowns.js
These are some more tests that would have picked up #285 and #283 .
=> cicd: More test coverage that would have caught recent issues

integration-tests/configs/trustedHeader/config.yaml, integration-tests/runner.mjs, integration-tests/test/general.mjs, integration-tests/test/trustedHeader.js
cicd: Reduce test flake and add lots more debugging info
=> cicd: Reduce test flake and add lots more debugging info

internal/executor/arguments.go, internal/onfileindir/fileindir.go
=> feature: extra args for fileindir

internal/onfileindir/fileindir.go
=> feature: Extra file info using onfileindir

webui.dev/js/ExecutionDialog.js
=> bugfix: #272 if the dialog is already open, close it

internal/executor/executor.go
This could be useful for passing values that you don't want passed on the command line.
=> feature: Arguments are now also passed as ENV variables

OliveTin.proto, internal/executor/executor.go, internal/grpcapi/grpcApi.go, webui.dev/index.html, webui.dev/js/ActionButton.js, webui.dev/js/ExecutionDialog.js, webui.dev/style.css
=> feature: Kill support in the UI

internal/config/config.go, internal/executor/executor.go
=> feature: Save logs! #174

internal/httpservers/restapi.go, internal/httpservers/restapi_auth_jwt_test.go, internal/httpservers/restapi_test.go
This cleans up a bunch of the REST API testing
=> fmt: Clean REST API Testing

webui.dev/index.html, webui.dev/js/marshaller.js
This allows you to link to http://server:1337/#Logs , http://server:1337/#Actions or http://server:1337/#MyDashboard (spaces are removed from dashboard names). Implements #306.
=> feature: #Logs and similar in the address bar to load relevant section (#306)

internal/stringvariables/entities.go, internal/stringvariables/map.go
=> bugfix: Race condition in stringvariables

OliveTin.proto, cmd/OliveTin/main.go, internal/entityfiles/entityfiles.go, internal/filehelper/file_change_notify.go, internal/websocket/websocket.go, webui.dev/js/marshaller.js, webui.dev/js/websocket.js
This is early support for refreshing the dashboard when entity files change. It also implements inotify debouncing that helps for the rest of OliveTin.
=> feature: Refresh dashboards when entity files change.

webui.dev/style.css
=> feature: Displays now have centered text, and "fit in" a bit better

internal/entityfiles/entityfiles.go, internal/filehelper/file_change_notify.go, webui.dev/js/marshaller.js, webui.dev/main.js
=> bugfix: #316 Entity file change debouce timer now uses delay after initial event

webui.dev/js/websocket.js
This is useful for people who host olivetin on /stuff/olivetin/ etc.
=> feature: Websocket URL is now relocatable

webui.dev/js/ExecutionDialog.js, webui.dev/js/marshaller.js, webui.dev/package-lock.json, webui.dev/package.json, webui.dev/style.css
Fixing a known bug from yesterday
=> bugfix: Terminal width fitting

webui.dev/style.css
=> fmt: Center argument-wrapper #327, point 5

config.yaml, internal/config/config.go, internal/updatecheck/updateCheck.go
=> Check for updates default disabled

internal/httpservers/webuiServer.go, internal/installationinfo/runtimeinfo.go, internal/installationinfo/sosreport.go, webui.dev/index.html, webui.dev/js/marshaller.js, webui.dev/style.css
This should make it a little easier for new users to OliveTin.
=> feature: New diagnostics page, showing SSH keys found.

webui.dev/style.css
Damned Chrome. Use Firefox and be happy :-)
=> bugfix: Output width in chrome

.github/workflows/build-snapshot.yml, .github/workflows/build-tag.yml, .gitignore, .goreleaser.yml, Dockerfile, Dockerfile.arm64, Dockerfile.armv7, config.yaml, internal/config/emoji.go, var/helper-actions/olivetin-get-dashboard-icons, var/helper-actions/olivetin-get-git-repo, var/helper-actions/olivetin-get-theme, var/helper-actions/olivetin-setup-easy-ssh
This PR introduces several helper scripts, most useful for when running OliveTin inside a container.
=> feature: Helper scripts for ssh, themes, etc

Dockerfile, Dockerfile.arm64
Updates to the latest supported version of Fedora.
=> feature: Container images upgraded to Fedora 40.

webui.dev/js/ArgumentForm.js
See title, andthanks @sirjmann92
=> feature: Argument labels will end with a :, unless they end with ?, : or .

.github/workflows/build-tag.yml
=> cicd: Update login-action

internal/entityfiles/entityfiles.go
This is necessary for bools, ints, floaks, slices, maps, etc.
=> feature: Entitiy data now serializes non-strings

Makefile, integration-tests/Makefile, internal/config/config_reloader.go
=> bugfix: use cross-platform module filepath to set usedConfigDir

.github/workflows/codeql-analysis.yml
=> cicd: Make grpc to fix codeql

internal/entityfiles/entityfiles.go
=> bugfix: #337 - Entity overwriting

webui.dev/style.css
=> feature: take full page and display footer at bottom of window

internal/httpservers/webuiServer.go, webui.dev/index.html, webui.dev/js/marshaller.js, webui.dev/js/websocket.js, webui.dev/main.js
=> feature: change all navigation to path based

internal/config/config.go, internal/httpservers/webuiServer.go, webui.dev/js/marshaller.js, webui.dev/style.css
=> feature: Sidebar hiding now pure CSS & theme reloading for devs

config.yaml
_Skipped some of these for a typo correction - hope that's ok_
=> Fixed typo in config.yml comments

internal/executor/executor.go
=> feature: Add OT_ vars to each execution

internal/executor/executor.go, internal/httpservers/restapi.go
=> bugfix: Null action map, causing crash on startup actions

webui.dev/js/marshaller.js
Repoed by MacPrince on Discord, many thanks.
=> bugfix: Dashboards with multiple spaces in the name could not be navigated properly

internal/acl/acl.go, internal/executor/executor.go, internal/grpcapi/grpcApi.go, internal/oncalendarfile/calendar.go, internal/oncron/cron.go, internal/onfileindir/fileindir.go, internal/onstartup/startup.go, internal/websocket/websocket.go, webui.dev/index.html, webui.dev/js/marshaller.js, webui.dev/style.css
=> feature: Log username with each request #422

webui.dev/index.html, webui.dev/style.css
=> feature: Slightly nicer looking logs and diagnostics pages

.goreleaser.yml
=> feature: Add riscv build!

OliveTin.proto, internal/acl/acl.go, internal/grpcapi/grpcApi.go, internal/grpcapi/local_user_login.go, internal/httpservers/restapi_auth_local.go, internal/httpservers/restapi_auth_oauth2.go
=> feature: Improved auth log messages

OliveTin.proto, internal/grpcapi/grpcApi.go
=> bugfix: #481 StartActionAndWait now allows arguments.
